version: '3'

services:
  promotion-db:
    image: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - ${PORT}:${PORT}
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: